#! /bin/bash
# /etc/init.d/player

### BEGIN INIT INFO
# Provides:          radio
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start an Internet radio player
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# Carry out specific functions when asked to by the system

case "$1" in
    start)
        echo "Starting Exea Media Radio..."

        # Run streaming
        echo 'Loading streaming radio...'
        sudo /home/pi/radio_pi/main.py & > /dev/null
        ;;
    stop)
        echo "Stopping Exea Media radio..."
        killall main.py > /dev/null
        if [ "$?" -eq 0 ]; then
            echo "Stopped"
        else
            echo "Error: Process is not running"
            exit 1
        fi

        ;;
    restart)
        echo "Restarting Exea Media radio..."
        service radio stop
        service radio start
        ;;
    *)
        echo "Usage: /etc/init.d/radio {start|stop|restart}"
        exit 1
        ;;
esac

exit 0